// This file is generated by Prismic local builder. Update with care!

export { default as ButtonSlice } from './ButtonSlice'
export { default as CardGridSlice } from './CardGridSlice'
export { default as CreateProjectsSlice } from './CreateProjectsSlice'
export { default as CtaBannerSlice } from './CtaBannerSlice'
export { default as CustomerLogoSlice } from './CustomerLogoSlice'
export { default as CustomerRatesSlice } from './CustomerRatesSlice'
export { default as KeyMetricsSlice } from './KeyMetricsSlice'
export { default as ProjectsGridSlice } from './ProjectsGridSlice'
export { default as SpacerSlice } from './SpacerSlice'
export { default as StartScreen } from './StartScreen'
export { default as TechnologiesSlice } from './TechnologiesSlice'
export { default as TextSlice } from './TextSlice'
