// This file is generated by Prismic local builder. Update with care!

export { default as BoilerplatesGridSlice } from './BoilerplatesGridSlice'
export { default as CtaBannerSlice } from './CtaBannerSlice'
export { default as CustomerLogoSlice } from './CustomerLogoSlice'
export { default as TextSlice } from './TextSlice'
