// This file is generated by Prismic local builder. Update with care!

export { default as CardGridSlice } from './CardGridSlice'
export { default as CtaBannerSlice } from './CtaBannerSlice'
export { default as CustomerLogoSlice } from './CustomerLogoSlice'
